# Generated by Django 4.2.23 on 2025-06-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0002_blogcategory_blogpost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmessage",
            old_name="submitted_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="contact_uploads/"),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="user_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
